{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yanisalfian.flutterphonedirectcaller",
    "module": "flutter_phone_direct_caller_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_phone_direct_caller_release-1.0.aar",
          "url": "flutter_phone_direct_caller_release-1.0.aar",
          "size": 8585,
          "sha512": "aad058f92ed543ee17592425bb86da38686195557d93e901d0cab4102b7a73ca70f48fedb0f3a646309481d5d25e28e8f2a6fdfa18f94b7ef91875b2b554935c",
          "sha256": "cce897c70300a628407575f504493a7f19ea891cb9402674e505c620264a53ee",
          "sha1": "c571c30d418d45e37866a368b4f537fc7777d239",
          "md5": "51180349633f46a5db203dc048eaae83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_phone_direct_caller_release-1.0.aar",
          "url": "flutter_phone_direct_caller_release-1.0.aar",
          "size": 8585,
          "sha512": "aad058f92ed543ee17592425bb86da38686195557d93e901d0cab4102b7a73ca70f48fedb0f3a646309481d5d25e28e8f2a6fdfa18f94b7ef91875b2b554935c",
          "sha256": "cce897c70300a628407575f504493a7f19ea891cb9402674e505c620264a53ee",
          "sha1": "c571c30d418d45e37866a368b4f537fc7777d239",
          "md5": "51180349633f46a5db203dc048eaae83"
        }
      ]
    }
  ]
}
