{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 12687,
          "sha512": "ad78e1f16a1757988a1ef5e45ea0e3a1c14e2956a8612da1b21098bfbe2253c2199cb3b71bc19290148dc3b8a8343f8f9fef43a41e1ad1d0c4bc8a1eabf5312e",
          "sha256": "75524dcae36f07ae907465ec4d8131e4af26c8d83edb721ec8edcb02f6a8fd77",
          "sha1": "428247bf5ffb163e42def001a4cec08ed01118bd",
          "md5": "8bc01f206e07973dc5bddccd54cd0cac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 12687,
          "sha512": "ad78e1f16a1757988a1ef5e45ea0e3a1c14e2956a8612da1b21098bfbe2253c2199cb3b71bc19290148dc3b8a8343f8f9fef43a41e1ad1d0c4bc8a1eabf5312e",
          "sha256": "75524dcae36f07ae907465ec4d8131e4af26c8d83edb721ec8edcb02f6a8fd77",
          "sha1": "428247bf5ffb163e42def001a4cec08ed01118bd",
          "md5": "8bc01f206e07973dc5bddccd54cd0cac"
        }
      ]
    }
  ]
}
