{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mr.flutter.plugin.filepicker",
    "module": "file_picker_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.aar",
          "url": "file_picker_release-1.0.aar",
          "size": 26481,
          "sha512": "bceef1794e48222653e54eeffb561b43053122d090a2b0d75ec41157d45a94c8804aabc8f02392d49c41158b1419ae08e67eacb855266fb189e8c22562315183",
          "sha256": "b4512805db44184fdcaf94f34662219140543b046ba52cace4d8dee637c291f0",
          "sha1": "b4687ef99f875b59566acee27bb175909e56f8b4",
          "md5": "3cac7193cadc1e66a76ed4d64ff7cb6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_picker_release-1.0.aar",
          "url": "file_picker_release-1.0.aar",
          "size": 26481,
          "sha512": "bceef1794e48222653e54eeffb561b43053122d090a2b0d75ec41157d45a94c8804aabc8f02392d49c41158b1419ae08e67eacb855266fb189e8c22562315183",
          "sha256": "b4512805db44184fdcaf94f34662219140543b046ba52cace4d8dee637c291f0",
          "sha1": "b4687ef99f875b59566acee27bb175909e56f8b4",
          "md5": "3cac7193cadc1e66a76ed4d64ff7cb6a"
        }
      ]
    }
  ]
}
