{
  "formatVersion": "1.1",
  "component": {
    "group": "com.salespandadm.app",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "app.meedu.flutter_facebook_auth",
          "module": "flutter_facebook_auth_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "zhuoyuan.li.fluttershareme",
          "module": "flutter_share_me_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "app.mylekha.webcontent_converter",
          "module": "webcontent_converter_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.incrediblezayed.file_saver",
          "module": "file_saver_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.linusu.flutter_web_auth_2",
          "module": "flutter_web_auth_2_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "name.avioli.unilinks",
          "module": "uni_links_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.yanisalfian.flutterphonedirectcaller",
          "module": "flutter_phone_direct_caller_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.imagegallerysaver",
          "module": "image_gallery_saver_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.material.plugins.dynamic_color",
          "module": "dynamic_color_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.odehbros.flutter_file_downloader",
          "module": "flutter_file_downloader_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutternativeimage",
          "module": "flutter_native_image_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.livelifedev.flutter_network_connectivity",
          "module": "flutter_network_connectivity_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dotsbit.flutter_facebook_keyhash.flutter_facebook_keyhash",
          "module": "flutter_facebook_keyhash_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "vn.hunghd.flutter.plugins.imagecropper",
          "module": "image_cropper_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_filex_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "android_generated",
          "module": "ffmpeg_kit_flutter_full_gpl_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.scer.pdf_renderer",
          "module": "pdfx_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.prongbang.screen_protector",
          "module": "screen_protector_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.whatsapp_share",
          "module": "whatsapp_share_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.kaichi.easy_pdf_viewer",
          "module": "easy_pdf_viewer_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 37460773,
          "sha512": "8504d17779f6faf8c9e7d55dbe8dc6f138fc14ee58b80e6f30a118eddf79ab9f23b4dab450be828142aad830b664916246753e529a6abf4e33b3b8111e167397",
          "sha256": "48ad141203715d94474cd3ef3be347bc3a9408f953324c656468d96155e95337",
          "sha1": "2500c9ba4ce60d46a5b1350657452e59e70ef929",
          "md5": "92f527d568714c1aec907875b53c7d22"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "app.meedu.flutter_facebook_auth",
          "module": "flutter_facebook_auth_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "zhuoyuan.li.fluttershareme",
          "module": "flutter_share_me_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "app.mylekha.webcontent_converter",
          "module": "webcontent_converter_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.incrediblezayed.file_saver",
          "module": "file_saver_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.linusu.flutter_web_auth_2",
          "module": "flutter_web_auth_2_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "name.avioli.unilinks",
          "module": "uni_links_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.yanisalfian.flutterphonedirectcaller",
          "module": "flutter_phone_direct_caller_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.imagegallerysaver",
          "module": "image_gallery_saver_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.material.plugins.dynamic_color",
          "module": "dynamic_color_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.odehbros.flutter_file_downloader",
          "module": "flutter_file_downloader_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutternativeimage",
          "module": "flutter_native_image_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.livelifedev.flutter_network_connectivity",
          "module": "flutter_network_connectivity_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dotsbit.flutter_facebook_keyhash.flutter_facebook_keyhash",
          "module": "flutter_facebook_keyhash_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "vn.hunghd.flutter.plugins.imagecropper",
          "module": "image_cropper_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_filex_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "android_generated",
          "module": "ffmpeg_kit_flutter_full_gpl_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.scer.pdf_renderer",
          "module": "pdfx_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.prongbang.screen_protector",
          "module": "screen_protector_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.whatsapp_share",
          "module": "whatsapp_share_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.kaichi.easy_pdf_viewer",
          "module": "easy_pdf_viewer_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 37460773,
          "sha512": "8504d17779f6faf8c9e7d55dbe8dc6f138fc14ee58b80e6f30a118eddf79ab9f23b4dab450be828142aad830b664916246753e529a6abf4e33b3b8111e167397",
          "sha256": "48ad141203715d94474cd3ef3be347bc3a9408f953324c656468d96155e95337",
          "sha1": "2500c9ba4ce60d46a5b1350657452e59e70ef929",
          "md5": "92f527d568714c1aec907875b53c7d22"
        }
      ]
    }
  ]
}
