{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dotsbit.flutter_facebook_keyhash.flutter_facebook_keyhash",
    "module": "flutter_facebook_keyhash_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_facebook_keyhash_debug-1.0.aar",
          "url": "flutter_facebook_keyhash_debug-1.0.aar",
          "size": 6248,
          "sha512": "08a8450a0242ac18a388fb8a45e79301a15d5c0117a268398ca5c869d2748d9dc3ed1c27d4aa43a7934212bed77ee9eb23f613b0fd6ac610269f9eebe18b6dff",
          "sha256": "83aab77f2257f500fcad97dc34765d617fca7bb529021546dacdacf010985734",
          "sha1": "a6f8c64268ff3a92cb87abff1b172ff27fe8eda0",
          "md5": "d952c91bf5c8d8e7a01481f4800bb6c3"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.50"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_facebook_keyhash_debug-1.0.aar",
          "url": "flutter_facebook_keyhash_debug-1.0.aar",
          "size": 6248,
          "sha512": "08a8450a0242ac18a388fb8a45e79301a15d5c0117a268398ca5c869d2748d9dc3ed1c27d4aa43a7934212bed77ee9eb23f613b0fd6ac610269f9eebe18b6dff",
          "sha256": "83aab77f2257f500fcad97dc34765d617fca7bb529021546dacdacf010985734",
          "sha1": "a6f8c64268ff3a92cb87abff1b172ff27fe8eda0",
          "md5": "d952c91bf5c8d8e7a01481f4800bb6c3"
        }
      ]
    }
  ]
}
