{
  "formatVersion": "1.1",
  "component": {
    "group": "com.livelifedev.flutter_network_connectivity",
    "module": "flutter_network_connectivity_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_network_connectivity_debug-1.0.aar",
          "url": "flutter_network_connectivity_debug-1.0.aar",
          "size": 10830,
          "sha512": "9dce2905b03c4865e91796f6d45e5e58c9019606eb16a92f392a984e7f2b291d9953a51a91e14fa698aa037bd37d269a5ed7d3dd9fc4343004d5131a4711d0fd",
          "sha256": "d037280a23c3b6859f8632db1d9c75732ff28f56769c9587af1c190744ecd6ec",
          "sha1": "213e7aae3ab079dc723c85b84cb4a54b1776900d",
          "md5": "ee8a05917bdd35a635b1365bdeb88476"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_network_connectivity_debug-1.0.aar",
          "url": "flutter_network_connectivity_debug-1.0.aar",
          "size": 10830,
          "sha512": "9dce2905b03c4865e91796f6d45e5e58c9019606eb16a92f392a984e7f2b291d9953a51a91e14fa698aa037bd37d269a5ed7d3dd9fc4343004d5131a4711d0fd",
          "sha256": "d037280a23c3b6859f8632db1d9c75732ff28f56769c9587af1c190744ecd6ec",
          "sha1": "213e7aae3ab079dc723c85b84cb4a54b1776900d",
          "md5": "ee8a05917bdd35a635b1365bdeb88476"
        }
      ]
    }
  ]
}
