{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xamdesign.safe_device",
    "module": "safe_device_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device_debug-1.0.aar",
          "url": "safe_device_debug-1.0.aar",
          "size": 76413,
          "sha512": "94032543502d1d4bd0a7c7af230751ddbafcc22b0cb094c614b71afdc61b6e55e4c357112b49b2858fdff3830405833b06a5471ab67246217340be53e0f15940",
          "sha256": "5b770a8c95021641eb850001d09487a9e4c69008d01af02d40207b62bb343d42",
          "sha1": "0c37e6645aa71b21e43392f315da65191bfadef5",
          "md5": "ca538c2ac5bacd5f741423eb7a8d1de0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.scottyab",
          "module": "rootbeer-lib",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v13",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "safe_device_debug-1.0.aar",
          "url": "safe_device_debug-1.0.aar",
          "size": 76413,
          "sha512": "94032543502d1d4bd0a7c7af230751ddbafcc22b0cb094c614b71afdc61b6e55e4c357112b49b2858fdff3830405833b06a5471ab67246217340be53e0f15940",
          "sha256": "5b770a8c95021641eb850001d09487a9e4c69008d01af02d40207b62bb343d42",
          "sha1": "0c37e6645aa71b21e43392f315da65191bfadef5",
          "md5": "ca538c2ac5bacd5f741423eb7a8d1de0"
        }
      ]
    }
  ]
}
