{
  "formatVersion": "1.1",
  "component": {
    "group": "zhuoyuan.li.fluttershareme",
    "module": "flutter_share_me_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share_me_release-1.0.aar",
          "url": "flutter_share_me_release-1.0.aar",
          "size": 22062,
          "sha512": "2729f058c580a6e6e9012e9d1913bc9e00ccceb406ab10c9028ad6f581dc9742fac01a85d786bc0d8724fd4dec90c56006bbd448773288d086af0a497905676c",
          "sha256": "2e5286248192d5199b0bd4e2bdfa914ae07f20eb5e8ad9576f25cf3dcce53ce9",
          "sha1": "a263fc5e7591d9532e9a16178a3366c024eeb64e",
          "md5": "0e3e5d94c20e4e326b245b9f80f9cc73"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "facebook-share",
          "version": {
            "requires": "5.15.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_share_me_release-1.0.aar",
          "url": "flutter_share_me_release-1.0.aar",
          "size": 22062,
          "sha512": "2729f058c580a6e6e9012e9d1913bc9e00ccceb406ab10c9028ad6f581dc9742fac01a85d786bc0d8724fd4dec90c56006bbd448773288d086af0a497905676c",
          "sha256": "2e5286248192d5199b0bd4e2bdfa914ae07f20eb5e8ad9576f25cf3dcce53ce9",
          "sha1": "a263fc5e7591d9532e9a16178a3366c024eeb64e",
          "md5": "0e3e5d94c20e4e326b245b9f80f9cc73"
        }
      ]
    }
  ]
}
