{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
    "module": "firebase_remote_config_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-1.0.aar",
          "url": "firebase_remote_config_release-1.0.aar",
          "size": 9205,
          "sha512": "93ea8bf06af75828e752dc02297e9e557edc8a27efecb04bfd35959e0aaea0fdcec318efa47771ca3bf93c33bff046ac8de9aa0e608343931d52722158add8a4",
          "sha256": "1fdb9c4eb10b1e4a48ed6ef1f882e65cd68ed922a551ea1b632bf5cf5538f524",
          "sha1": "0c13aa77825f9635034a9ca3daaa49bbb7239dcf",
          "md5": "eec8e520226e1ae23a0f6a77b3930fa4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "30.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_remote_config_release-1.0.aar",
          "url": "firebase_remote_config_release-1.0.aar",
          "size": 9205,
          "sha512": "93ea8bf06af75828e752dc02297e9e557edc8a27efecb04bfd35959e0aaea0fdcec318efa47771ca3bf93c33bff046ac8de9aa0e608343931d52722158add8a4",
          "sha256": "1fdb9c4eb10b1e4a48ed6ef1f882e65cd68ed922a551ea1b632bf5cf5538f524",
          "sha1": "0c13aa77825f9635034a9ca3daaa49bbb7239dcf",
          "md5": "eec8e520226e1ae23a0f6a77b3930fa4"
        }
      ]
    }
  ]
}
