{
  "formatVersion": "1.1",
  "component": {
    "group": "com.prongbang.screen_protector",
    "module": "screen_protector_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "screen_protector_debug-1.0.aar",
          "url": "screen_protector_debug-1.0.aar",
          "size": 5408,
          "sha512": "23e9b3a064c70e0481f62a6b4664afe5f5e9b0a63c5714cae70f2fde0c77b5e0bac131851c5b1f6eb9135e2444e5f478618c7a106b6085d24c6e9050ea909117",
          "sha256": "1004125ea3708461acb1ef55532589415bf692ba39e13b91d130da76b1dc7603",
          "sha1": "76d23586a436c4aa9069188255128163738795d0",
          "md5": "8b1cf8d30adf0d9adf07c3690a27095d"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "screen_protector_debug-1.0.aar",
          "url": "screen_protector_debug-1.0.aar",
          "size": 5408,
          "sha512": "23e9b3a064c70e0481f62a6b4664afe5f5e9b0a63c5714cae70f2fde0c77b5e0bac131851c5b1f6eb9135e2444e5f478618c7a106b6085d24c6e9050ea909117",
          "sha256": "1004125ea3708461acb1ef55532589415bf692ba39e13b91d130da76b1dc7603",
          "sha1": "76d23586a436c4aa9069188255128163738795d0",
          "md5": "8b1cf8d30adf0d9adf07c3690a27095d"
        }
      ]
    }
  ]
}
