{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9790,
          "sha512": "76ef8b90d50aeec81831cfc218f4f48db700a2f3bbebe2cc6c827d6850ae3f7863660caf2f95de6a41e7cf1d7faa0ce260e5d6a4c102e2d9e3c254ff4a16e9b9",
          "sha256": "32721c45e9e809002d0dd05e7e15e7b86d11d3e8586df653643ae70f88acba36",
          "sha1": "e3cacd456bb9f561d67942797aed5b22d301da49",
          "md5": "11fd8be70f8dc2a9c756fba2ae8b166f"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_debug-1.0.aar",
          "url": "device_info_plus_debug-1.0.aar",
          "size": 9790,
          "sha512": "76ef8b90d50aeec81831cfc218f4f48db700a2f3bbebe2cc6c827d6850ae3f7863660caf2f95de6a41e7cf1d7faa0ce260e5d6a4c102e2d9e3c254ff4a16e9b9",
          "sha256": "32721c45e9e809002d0dd05e7e15e7b86d11d3e8586df653643ae70f88acba36",
          "sha1": "e3cacd456bb9f561d67942797aed5b22d301da49",
          "md5": "11fd8be70f8dc2a9c756fba2ae8b166f"
        }
      ]
    }
  ]
}
