{
  "formatVersion": "1.1",
  "component": {
    "group": "com.salespandadm.app",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "app.meedu.flutter_facebook_auth",
          "module": "flutter_facebook_auth_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "zhuoyuan.li.fluttershareme",
          "module": "flutter_share_me_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "app.mylekha.webcontent_converter",
          "module": "webcontent_converter_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.incrediblezayed.file_saver",
          "module": "file_saver_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.linusu.flutter_web_auth_2",
          "module": "flutter_web_auth_2_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "name.avioli.unilinks",
          "module": "uni_links_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.yanisalfian.flutterphonedirectcaller",
          "module": "flutter_phone_direct_caller_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.imagegallerysaver",
          "module": "image_gallery_saver_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.material.plugins.dynamic_color",
          "module": "dynamic_color_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.odehbros.flutter_file_downloader",
          "module": "flutter_file_downloader_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutternativeimage",
          "module": "flutter_native_image_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.livelifedev.flutter_network_connectivity",
          "module": "flutter_network_connectivity_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dotsbit.flutter_facebook_keyhash.flutter_facebook_keyhash",
          "module": "flutter_facebook_keyhash_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "vn.hunghd.flutter.plugins.imagecropper",
          "module": "image_cropper_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_filex_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "android_generated",
          "module": "ffmpeg_kit_flutter_full_gpl_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.scer.pdf_renderer",
          "module": "pdfx_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.prongbang.screen_protector",
          "module": "screen_protector_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.whatsapp_share",
          "module": "whatsapp_share_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.kaichi.easy_pdf_viewer",
          "module": "easy_pdf_viewer_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 25969132,
          "sha512": "ec53285150bf80668b084844264b024daf4a0198f87c68481cca25e8591dcf68655a8d56cbaf756782593395599c42af5e72276f4150dbc3d82fa2e6ce6325e8",
          "sha256": "cba15ee0ce4dbc7533fb4e9e2c6c43c8cb70c9e32c37587d135948c1ec526bb8",
          "sha1": "f4a146059c89985728cfed1d64360e3fe8ba5280",
          "md5": "ff9eb7e4e1d72d37cff5b637b90dc1c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mr.flutter.plugin.filepicker",
          "module": "file_picker_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.jhomlala.better_player.better_player",
          "module": "better_player_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "app.meedu.flutter_facebook_auth",
          "module": "flutter_facebook_auth_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.xamdesign.safe_device",
          "module": "safe_device_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "creativemaybeno.wakelock",
          "module": "wakelock_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "zhuoyuan.li.fluttershareme",
          "module": "flutter_share_me_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "app.mylekha.webcontent_converter",
          "module": "webcontent_converter_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.incrediblezayed.file_saver",
          "module": "file_saver_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.linusu.flutter_web_auth_2",
          "module": "flutter_web_auth_2_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "name.avioli.unilinks",
          "module": "uni_links_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebasemessaging",
          "module": "firebase_messaging_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.yanisalfian.flutterphonedirectcaller",
          "module": "flutter_phone_direct_caller_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.crashlytics",
          "module": "firebase_crashlytics_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.imagegallerysaver",
          "module": "image_gallery_saver_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.material.plugins.dynamic_color",
          "module": "dynamic_color_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.odehbros.flutter_file_downloader",
          "module": "flutter_file_downloader_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.flutternativeimage",
          "module": "flutter_native_image_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.googlesignin",
          "module": "google_sign_in_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.livelifedev.flutter_network_connectivity",
          "module": "flutter_network_connectivity_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dotsbit.flutter_facebook_keyhash.flutter_facebook_keyhash",
          "module": "flutter_facebook_keyhash_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "vn.hunghd.flutter.plugins.imagecropper",
          "module": "image_cropper_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.crazecoder.openfile",
          "module": "open_filex_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "android_generated",
          "module": "ffmpeg_kit_flutter_full_gpl_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.scer.pdf_renderer",
          "module": "pdfx_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.analytics",
          "module": "firebase_analytics_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.prongbang.screen_protector",
          "module": "screen_protector_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.firebaseremoteconfig",
          "module": "firebase_remote_config_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "co.quis.flutter_contacts",
          "module": "flutter_contacts_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.example.whatsapp_share",
          "module": "whatsapp_share_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.kaichi.easy_pdf_viewer",
          "module": "easy_pdf_viewer_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 25969132,
          "sha512": "ec53285150bf80668b084844264b024daf4a0198f87c68481cca25e8591dcf68655a8d56cbaf756782593395599c42af5e72276f4150dbc3d82fa2e6ce6325e8",
          "sha256": "cba15ee0ce4dbc7533fb4e9e2c6c43c8cb70c9e32c37587d135948c1ec526bb8",
          "sha1": "f4a146059c89985728cfed1d64360e3fe8ba5280",
          "md5": "ff9eb7e4e1d72d37cff5b637b90dc1c0"
        }
      ]
    }
  ]
}
