{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-1.0.aar",
          "url": "flutter_local_notifications_debug-1.0.aar",
          "size": 68046,
          "sha512": "2065a674c2085bd0b64661fd7391a536d2c473d88fa7e1e15fcacf9dabcaec21bce29538b0cbec6bb60522027559d64926ab5b97cadc4c98b3e24e5deb076191",
          "sha256": "59da110e2e86b40c1c3632dcf842f1443f10c6ca512c1909faf74d78e3b58a8b",
          "sha1": "fdeab7d49424568aa4f95d82b4fe0db3223fc147",
          "md5": "3b12331ef2841a5cd6998c364f48d3b5"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_debug-1.0.aar",
          "url": "flutter_local_notifications_debug-1.0.aar",
          "size": 68046,
          "sha512": "2065a674c2085bd0b64661fd7391a536d2c473d88fa7e1e15fcacf9dabcaec21bce29538b0cbec6bb60522027559d64926ab5b97cadc4c98b3e24e5deb076191",
          "sha256": "59da110e2e86b40c1c3632dcf842f1443f10c6ca512c1909faf74d78e3b58a8b",
          "sha1": "fdeab7d49424568aa4f95d82b4fe0db3223fc147",
          "md5": "3b12331ef2841a5cd6998c364f48d3b5"
        }
      ]
    }
  ]
}
