{
  "formatVersion": "1.1",
  "component": {
    "group": "com.incrediblezayed.file_saver",
    "module": "file_saver_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "file_saver_release-1.0.aar",
          "url": "file_saver_release-1.0.aar",
          "size": 19215,
          "sha512": "3b90ff5a837fc05b7b109b0a3455a2f61bd8b629b49f151a1bbf76b696b3192d4d96bbc8e0f865ad5bfe70b57176d511289ca3039b90d374de7f6d30a513fba2",
          "sha256": "daac5bdf56e576d4e9a63a47fd064fda6660f519966752406974963810baecf2",
          "sha1": "2a5315ad28b9c636d8b821cfd3ca8d8bc0356ee0",
          "md5": "42cfde9c1f41a7ab3a3b69f8b28f48ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "file_saver_release-1.0.aar",
          "url": "file_saver_release-1.0.aar",
          "size": 19215,
          "sha512": "3b90ff5a837fc05b7b109b0a3455a2f61bd8b629b49f151a1bbf76b696b3192d4d96bbc8e0f865ad5bfe70b57176d511289ca3039b90d374de7f6d30a513fba2",
          "sha256": "daac5bdf56e576d4e9a63a47fd064fda6660f519966752406974963810baecf2",
          "sha1": "2a5315ad28b9c636d8b821cfd3ca8d8bc0356ee0",
          "md5": "42cfde9c1f41a7ab3a3b69f8b28f48ee"
        }
      ]
    }
  ]
}
