{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebase.crashlytics",
    "module": "firebase_crashlytics_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_crashlytics_release-1.0.aar",
          "url": "firebase_crashlytics_release-1.0.aar",
          "size": 16441,
          "sha512": "fde2b3e898f3f92b8d59e799c78b8cf0b017791e354fca8f59a5839b6df03ba1c7af30ef27f57c40a524990df9f01dd1a609d188a64aaa21af1e0a0d19ad5f24",
          "sha256": "667abcb0dee0c20af0bdcd8f133f345e5e2fe10540e0a32b2566ea56079f7481",
          "sha1": "49638fa5cace2c9d41c0b25c800ad2452a22f3ea",
          "md5": "7590f04087c689a9b0852ddc3f6f4ee1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "30.5.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics"
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_crashlytics_release-1.0.aar",
          "url": "firebase_crashlytics_release-1.0.aar",
          "size": 16441,
          "sha512": "fde2b3e898f3f92b8d59e799c78b8cf0b017791e354fca8f59a5839b6df03ba1c7af30ef27f57c40a524990df9f01dd1a609d188a64aaa21af1e0a0d19ad5f24",
          "sha256": "667abcb0dee0c20af0bdcd8f133f345e5e2fe10540e0a32b2566ea56079f7481",
          "sha1": "49638fa5cace2c9d41c0b25c800ad2452a22f3ea",
          "md5": "7590f04087c689a9b0852ddc3f6f4ee1"
        }
      ]
    }
  ]
}
