{
  "formatVersion": "1.1",
  "component": {
    "group": "name.avioli.unilinks",
    "module": "uni_links_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "uni_links_debug-1.0.aar",
          "url": "uni_links_debug-1.0.aar",
          "size": 6502,
          "sha512": "5ed17fb5200ff391bac5eb5acc4c0f04a242f9cbb657c64ee4c7f5cf0286cba5ce22ee08712afddc538b592e6d25a234b4555cdfa0b984e7f2519573239c9f22",
          "sha256": "8723279216ebcceeb560501b0a35f5bbc462fd373bdb8bb54c315f94db22bb1c",
          "sha1": "c0bebeb33c6b40dc8012c1906658b8110637fc68",
          "md5": "8ee824881a74b387e523737d2c0f8fea"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "uni_links_debug-1.0.aar",
          "url": "uni_links_debug-1.0.aar",
          "size": 6502,
          "sha512": "5ed17fb5200ff391bac5eb5acc4c0f04a242f9cbb657c64ee4c7f5cf0286cba5ce22ee08712afddc538b592e6d25a234b4555cdfa0b984e7f2519573239c9f22",
          "sha256": "8723279216ebcceeb560501b0a35f5bbc462fd373bdb8bb54c315f94db22bb1c",
          "sha1": "c0bebeb33c6b40dc8012c1906658b8110637fc68",
          "md5": "8ee824881a74b387e523737d2c0f8fea"
        }
      ]
    }
  ]
}
