{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.whatsapp_share",
    "module": "whatsapp_share_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "whatsapp_share_release-1.0.aar",
          "url": "whatsapp_share_release-1.0.aar",
          "size": 6823,
          "sha512": "87444583241abbe41eb772080ea1c8526134b74157d5efbb3ca9298c4b6b4af908ded8da367d5373c7015ea279f4f964d62c1cc4f2469b3077924f53e6c8338b",
          "sha256": "7a7ffdec1d3f4ab3c10e61c60790c99e0f53a4bb91821093f0739a571edc13d8",
          "sha1": "a4ae5091c7a6d5764643bcb07ba0155e344a0424",
          "md5": "623845d52c99393835543acd7e7e39b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "whatsapp_share_release-1.0.aar",
          "url": "whatsapp_share_release-1.0.aar",
          "size": 6823,
          "sha512": "87444583241abbe41eb772080ea1c8526134b74157d5efbb3ca9298c4b6b4af908ded8da367d5373c7015ea279f4f964d62c1cc4f2469b3077924f53e6c8338b",
          "sha256": "7a7ffdec1d3f4ab3c10e61c60790c99e0f53a4bb91821093f0739a571edc13d8",
          "sha1": "a4ae5091c7a6d5764643bcb07ba0155e344a0424",
          "md5": "623845d52c99393835543acd7e7e39b0"
        }
      ]
    }
  ]
}
