{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-1.0.aar",
          "url": "image_picker_android_debug-1.0.aar",
          "size": 69162,
          "sha512": "15081706562d9e58fad9536bcb5b71367656972489bd930171a05e7c793d13f714446fe3d26532857b2c96befe4fdd585ae08cc4d8580425f10fd8a03541d9b8",
          "sha256": "09a05afa3094cff47b6d60df86df9407952860af4f6411cb09d3de8727511df6",
          "sha1": "c5c1846e801fc911ef0a5f4afcb72eaa437d8509",
          "md5": "eb3cbf3fd8c83f398091e2fd7ef7c743"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-1.0.aar",
          "url": "image_picker_android_debug-1.0.aar",
          "size": 69162,
          "sha512": "15081706562d9e58fad9536bcb5b71367656972489bd930171a05e7c793d13f714446fe3d26532857b2c96befe4fdd585ae08cc4d8580425f10fd8a03541d9b8",
          "sha256": "09a05afa3094cff47b6d60df86df9407952860af4f6411cb09d3de8727511df6",
          "sha1": "c5c1846e801fc911ef0a5f4afcb72eaa437d8509",
          "md5": "eb3cbf3fd8c83f398091e2fd7ef7c743"
        }
      ]
    }
  ]
}
