{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7824,
          "sha512": "062cb294182ffe31674de2ce95983f288159f6c7482908d610864dfebddabedede5ac40a294ca7d7038a4ce90741a97056512b72e5e9a4196a5376521024cc71",
          "sha256": "91aab41935c7ef2f7d8ea79aedc2de9044750ba4a2ae3ec7473c142391d96aba",
          "sha1": "a57dd7fa142845b6e7baba23e0cf42b56dbc6b6b",
          "md5": "2cb545e0ba538579e43ba70978bf667f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7824,
          "sha512": "062cb294182ffe31674de2ce95983f288159f6c7482908d610864dfebddabedede5ac40a294ca7d7038a4ce90741a97056512b72e5e9a4196a5376521024cc71",
          "sha256": "91aab41935c7ef2f7d8ea79aedc2de9044750ba4a2ae3ec7473c142391d96aba",
          "sha1": "a57dd7fa142845b6e7baba23e0cf42b56dbc6b6b",
          "md5": "2cb545e0ba538579e43ba70978bf667f"
        }
      ]
    }
  ]
}
