{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.hunghd.flutter.plugins.imagecropper",
    "module": "image_cropper_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "image_cropper_release-1.0.aar",
          "url": "image_cropper_release-1.0.aar",
          "size": 25335,
          "sha512": "a14ac6e1ba27665fd0577d0ca93849b569bab1e25f748a60a8c7142fc6b705d8e1c11d5063b6c4d471b05e6f58b485cf5739da245548e22efb6e69c9104d296f",
          "sha256": "2bbebc49c24f4e2469fd34a7c54f50c773530c3a776b7766331b967a40bbf40d",
          "sha1": "0ecdc3e536cdc98a9504f4c0969a91592751e044",
          "md5": "d75064c8de01e50ed530009f14ef069d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "com.github.yalantis",
          "module": "ucrop",
          "version": {
            "requires": "2.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "image_cropper_release-1.0.aar",
          "url": "image_cropper_release-1.0.aar",
          "size": 25335,
          "sha512": "a14ac6e1ba27665fd0577d0ca93849b569bab1e25f748a60a8c7142fc6b705d8e1c11d5063b6c4d471b05e6f58b485cf5739da245548e22efb6e69c9104d296f",
          "sha256": "2bbebc49c24f4e2469fd34a7c54f50c773530c3a776b7766331b967a40bbf40d",
          "sha1": "0ecdc3e536cdc98a9504f4c0969a91592751e044",
          "md5": "d75064c8de01e50ed530009f14ef069d"
        }
      ]
    }
  ]
}
