{
  "formatVersion": "1.1",
  "component": {
    "group": "app.mylekha.webcontent_converter",
    "module": "webcontent_converter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "webcontent_converter_release-1.0.aar",
          "url": "webcontent_converter_release-1.0.aar",
          "size": 28093,
          "sha512": "18ab22621113297d412c64a7b014e559c26d46b3e55795f9c79f3f664c45569caada814cbe11bbda917d7a4c8379788cdf6b6ef4a05ad3b6c12c93b78cdaf1d9",
          "sha256": "627531eaf6eee1f1d8f8e8a665673e4ea732d69710560ed4de62ba0f94a14abe",
          "sha1": "4452f58fcd57849fa950d598bbc8bb730a1cca0c",
          "md5": "15c499d7f774b9241f6eecf491fd3a72"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "webcontent_converter_release-1.0.aar",
          "url": "webcontent_converter_release-1.0.aar",
          "size": 28093,
          "sha512": "18ab22621113297d412c64a7b014e559c26d46b3e55795f9c79f3f664c45569caada814cbe11bbda917d7a4c8379788cdf6b6ef4a05ad3b6c12c93b78cdaf1d9",
          "sha256": "627531eaf6eee1f1d8f8e8a665673e4ea732d69710560ed4de62ba0f94a14abe",
          "sha1": "4452f58fcd57849fa950d598bbc8bb730a1cca0c",
          "md5": "15c499d7f774b9241f6eecf491fd3a72"
        }
      ]
    }
  ]
}
